use_frameworks!

platform :ios, '9.0'

target 'TMBRabbitMQ_Example' do
  pod 'TMBRabbitMQ', :path => '../'

  target 'TMBRabbitMQ_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
